version: "3"

networks:
  proxy:
    external: true

services:
  bin:
    build:
      context: .
    image: jnsgruk/bin:latest
    container_name: bin
    networks:
      - proxy
    expose:
      - 8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bin-http.rule=Host(`bin.somedomain.com`)"
      - "traefik.http.routers.bin-http.entrypoints=web"
      - "traefik.http.routers.bin-http.middlewares=https-redirect@docker"
      - "traefik.http.routers.bin-https.rule=Host(`bin.somedomain.com`)"
      - "traefik.http.routers.bin-https.entrypoints=websecure"
      - "traefik.http.routers.bin-https.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.bin-https.tls=true"
    restart: always
