# Used to redirect traffic from a TCP router to wstunnel running on the host
[tcp.services]
  [tcp.services.wstunnel.loadBalancer]
    [[tcp.services.wstunnel.loadBalancer.servers]]
      address = "host.docker.internal:4443"

[tcp.routers]
  [tcp.routers.wstunnel]
    rule = "HostSNI(`wss.somedomain.com`)"
    service = "wstunnel"
    [tcp.routers.wstunnel.tls]
      passthrough = true