version: "3"

networks:
  proxy:
    external: true
  socket_net:

services:
  # This is used so that Traefik doesn't mount the Docker socket directly!
  socket-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: socket-proxy
    privileged: yes
    environment:
      - CONTAINERS=1
    expose:
      - 2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - socket_net
    restart: always

  proxy:
    image: traefik:v2.0
    container_name: traefik
    entrypoint:
      - /bin/ash
      - -c
      - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && traefik traefik
    environment:
      TRAEFIK_API: "true"
      TRAEFIK_API_DASHBOARD: "true"
      TRAEFIK_PROVIDERS_DOCKER: "true"
      TRAEFIK_PROVIDERS_DOCKER_ENDPOINT: "tcp://socket-proxy:2375"
      TRAEFIK_PROVIDERS_DOCKER_NETWORK: "proxy"
      TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT: "false"
      TRAEFIK_PROVIDERS_FILE_FILENAME: "/etc/traefik/config.toml"
      TRAEFIK_PROVIDERS_FILE_WATCH: "true"
      TRAEFIK_ENTRYPOINTS_web: "true"
      TRAEFIK_ENTRYPOINTS_web_ADDRESS: ":80"
      TRAEFIK_ENTRYPOINTS_websecure: "true"
      TRAEFIK_ENTRYPOINTS_websecure_ADDRESS: ":443"
      TRAEFIK_CERTIFICATESRESOLVERS_MYHTTPCHALLENGE_ACME_HTTPCHALLENGE: "true"
      TRAEFIK_CERTIFICATESRESOLVERS_MYHTTPCHALLENGE_ACME_HTTPCHALLENGE_ENTRYPOINT: "web"
      TRAEFIK_CERTIFICATESRESOLVERS_MYHTTPCHALLENGE_ACME_EMAIL: "jonseager@gmail.com"
      TRAEFIK_CERTIFICATESRESOLVERS_MYHTTPCHALLENGE_ACME_STORAGE: "/letsencrypt/acme.json"
    ports:
      - 80:80
      - 443:443
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # MAKE SURE TO REPLACE CREDS ON THE FOLLOWING LINE
      # Use: echo $(htpasswd -nb user password) | sed -e s/\\$/\\$\\$/g
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:somehash"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`monitor.somedomain.com`)"
      - "traefik.http.routers.traefik.middlewares=https-redirect@docker"
      - "traefik.http.routers.traefik-https.entrypoints=websecure"
      - "traefik.http.routers.traefik-https.rule=Host(`monitor.somedomain.com`)"
      - "traefik.http.routers.traefik-https.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.traefik-https.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-https.tls=true"
      - "traefik.http.routers.traefik-https.service=api@internal"
    volumes:
      - /opt/services/state/traefik/letsencrypt:/letsencrypt
      - /opt/services/config/traefik/config.toml:/etc/traefik/config.toml
    networks:
      - proxy
      - socket_net
    restart: always
