api:
  dashboard: true

providers:
  docker:
    endpoint: tcp://socket-proxy:2375
    network: proxy
    exposedByDefault: false
  file:
    filename: /etc/traefik/config.yml
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myhttpchallenge:
    acme:
      email: jonseager@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
