version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  nc-app:
    image: nextcloud:latest
    container_name: nc-app
    networks:
      - proxy
      - internal
    depends_on:
      - nc-db
      - nc-redis
    # THESE CAN BE USED TO AUTOCONFIGURE IF BUILDING FROM SCRATCH
    # environment:
    #   - MYSQL_HOST=nc-db
    #   - MYSQL_USER=nextcloud
    #   - MYSQL_PASSWORD=secure_password
    #   - MYSQL_DATABASE=nextcloud
    #   - REDIS_HOST=nc-redis
    #   - NEXTCLOUD_ADMIN_USER=admin
    #   - NEXTCLOUD_ADMIN_PASSWORD=secure_password
    #   - NEXTCLOUD_TRUSTED_DOMAINS=cloud.somedomain.com
    volumes:
      - /opt/services/state/nextcloud/app/config:/var/www/html/config
      - /opt/services/state/nextcloud/app/custom_apps:/var/www/html/custom_apps
      - /opt/services/state/nextcloud/data:/var/www/html/data
      - /opt/services/state/nextcloud/app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nc-http.entrypoints=web"
      - "traefik.http.routers.nc-http.rule=Host(`cloud.somedomain.com`)"
      - "traefik.http.routers.nc-http.middlewares=https-redirect@docker"
      - "traefik.http.routers.nc-https.entrypoints=websecure"
      - "traefik.http.routers.nc-https.rule=Host(`cloud.somedomain.com`)"
      - "traefik.http.routers.nc-https.middlewares=nc-rep,nc-header"
      - "traefik.http.routers.nc-https.tls.certresolver=myhttpchallenge"
      - "traefik.http.routers.nc-https.tls=true"
      - "traefik.http.middlewares.nc-rep.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nc-rep.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nc-rep.redirectregex.permanent=true"
      - "traefik.http.middlewares.nc-header.headers.customFrameOptionsValue=SAMEORIGIN"
    restart: unless-stopped

  nc-redis:
    image: redis
    container_name: nc-redis
    restart: always

  nc-db:
    image: mariadb
    container_name: nc-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    # THESE CAN BE USED TO AUTOCONFIGURE IF BUILDING FROM SCRATCH
    # environment:
    # - MYSQL_ROOT_PASSWORD=secure_password
    # - MYSQL_USER=nextcloud
    # - MYSQL_PASSWORD=secure_password
    # - MYSQL_DATABASE=nextcloud
    networks:
      - internal
    volumes:
      - /opt/services/state/nextcloud/db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
